### ISSUE TITLE
Conda environment yml conflict

### ISSUE THREAD

**Issue by pooyanrg** [amolchanov86/quad_sim2multireal#3]
The issue has been solved.

**Comment by ianikpark** [comment]
Hi, @Pooyanrmz. Would you be able to share how you resolved the conflict? I'm also experiencing a conflict when creating an environment using [conda_env.yml](https://github.com/amolchanov86/quad_sim2multireal/blob/master/conda_env.yml).

**Comment by pooyanrg** [comment]
Hi, the issue occurred during creating env from .yml file complaining about conflicts in package dependencies. After digging through the internet and checking garage dependencies I found that the env file is produced with miniconda2(it could be anaconda2 either). But the point is when you try to create env, the default script will download the latest version of miniconda2. So I did the steps below to resolve it:
1.download anaconda2-2019-03 for Linux from conda repo and install.
2.in garage/scripts/setup_linux.sh comment the lines 190 to 205. this will skip configuring conda with the latest version.
3.install garage as in Readme file. you may need to add conda.sh path to your bashrc since in my case it was not done automatically.
4.now you can go through the remaining steps of installing S2R.
let me know if you were able to resolve the issue using these steps.

**Comment by ianikpark** [comment]
Thanks for the reply @Pooyanrmz! I finally got it to work.

For those who experience the same problem in the future, here are the steps I took:

1. [Uninstall](https://conda.io/projects/conda/en/latest/user-guide/install/linux.html#uninstalling-anaconda-or-miniconda) Miniconda2 (the latest stable version: 4.8.2 as of March 1, 2021)
```
cd ~
rm -rf miniconda2
```

2. [Download](https://conda.io/projects/conda/en/latest/user-guide/install/linux.html#installing-on-linux) Miniconda2 version **4.6.14** released in April 2019. Find the right platform version from the official [repository](https://repo.anaconda.com/miniconda/). For Linux 64-bit:
```
wget https://repo.anaconda.com/miniconda/Miniconda2-4.6.14-Linux-x86_64.sh
```

3. Run the downloaded installation script.
```
bash Miniconda2-4.6.14-Linux-x86_64.sh
```

4. Follow the prompts on the installer screens. I accepted the defaults.

5. Add the Miniconda2 directory to your PATH environment variable in `.bashrc`. Change `<username>` to yours.
```
export PATH="/home/<username>/miniconda2/bin:$PATH"
```

6. Apply the change in `.bashrc`.
```
source .bashrc
```

7. Redo [Step 4: Create a new conda environment](https://github.com/amolchanov86/quad_sim2multireal#step-4).

FYI: This problem seems to be happening with the recent versions of [conda](https://github.com/conda/conda). Here's a relevant [issue](https://github.com/conda/conda/issues/9367) filed to [conda](https://github.com/conda/conda). Downgrading solved the problem!
